import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500"],
  style: "normal",
  variable: "--poppins", 
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ryse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-[#1E1E1E]">
      <body className={`${poppins.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
